[package]
name = "rust-ping-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pnet = "0.34.0"
serde = "1.0.188"
serde_json = "1.0.107"
